version: "3.8"

services:
  backend-dev:
    container_name: backend-dev
    restart: unless-stopped
    build:
      context: ./backend
      target: dev
      args:
        - PORT:${PORT:-8080}
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    env_file:
      - .env
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules

  frontend-dev:
    container_name: frontend-dev
    build:
      context: ./frontend
      target: dev
    restart: always
    stdin_open: true
    ports:
      - "5173:5173"
    depends_on:
      - backend-dev
    environment:
      - CHOKIDAR_USEPOLLING=true # Necesario para que Vite detecte cambios en Docker
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
volumes:
  backend_node_modules:
  frontend_node_modules:
