version: "3.8"

services:
  backend-dev:
    container_name: backend-dev
    restart: unless-stopped
    build:
      context: ./backend
      target: dev
      args:
        - PORT:${PORT}
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    volumes:
      - ./backend:/app
      - node_modules:/app/node_modules

  frontend-dev:
    container_name: frontend-dev
    build:
      context: ./frontend
      target: dev
    restart: always
    stdin_open: true
    ports:
      - "5173:5173"
    depends_on:
      - backend-dev
    environment:
      - CHOKIDAR_USEPOLLING=true # Necesario para que Vite detecte cambios en Docker
    volumes:
      - ./frontend:/app
      - /app/node_modules
volumes:
  node_modules:
